<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Jose Aranega Fernandez
Curso: 1 DAW 
Fecha: 17/03/25 
Ejercicio: Ejercicio 1 
-->
<!DOCTYPE albumesMortadelo [
  <!ELEMENT albumesMortadelo (album*)>
  <!ELEMENT album (nombre, fecha)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT fecha (#PCDATA)>
]>
<albumesMortadelo>
  <album>
    <nombre>El sulfato at√≥mico</nombre>
    <fecha>1969</fecha>
  </album>
  <album>
    <nombre>La caja de diez cerrojos</nombre>
    <fecha>1971</fecha>
  </album>
  <album>
    <nombre>El otro yo del profesor Bacterio</nombre>
    <fecha>1973</fecha>
  </album>
  <album>
    <nombre>Los cacharros majaretas</nombre>
    <fecha>1974</fecha>
  </album>
</albumesMortadelo>
