<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Jose Aranega Fernandez
Curso: 1 DAW 
Fecha: 17/03/25 
Ejercicio: Ejercicio 1 
-->
<!DOCTYPE aeropuertos [
  <!ELEMENT aeropuertos (aeropuerto*)>
  <!ELEMENT aeropuerto (nombre, cerrado?)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT cerrado (#PCDATA)>
]>
<aeropuertos>
  <aeropuerto>
    <nombre>Berlin Schönefeld (SFX)</nombre>
  </aeropuerto>
  <aeropuerto>
    <nombre>Berlín Tempelhof (THF)</nombre>
    <cerrado />
  </aeropuerto>
</aeropuertos>
