<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Jose Aranega Fernandez
Curso: 1 DAW 
Fecha: 17/03/25 
Ejercicio: Ejercicio 1 
-->

<!DOCTYPE reyesEspañoles [
  <!ELEMENT reyesEspañoles (rey | reina)*>
  <!ELEMENT rey (nombre, padre, madre)>
  <!ELEMENT reina (nombre, padre, madre)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT padre (#PCDATA)>
  <!ELEMENT madre (#PCDATA)>
]>
<reyesEspañoles>
  <rey>
    <nombre>Felipe III</nombre>
    <padre>Felipe II</padre>
    <madre>Ana de Austria</madre>
  </rey>
  <reina>
    <nombre>Juana la Loca</nombre>
    <padre>Fernando el Católico</padre>
    <madre>Isabel la Católica</madre>
  </reina>
  <rey>
    <nombre>Carlos I</nombre>
    <padre>Felipe el Hermoso</padre>
    <madre>Juan la Loca</madre>
  </rey>
</reyesEspañoles>
