=== josetillo/marcas/Validacion 1/liga.dtd
<!ELEMENT liga (jugador+)>
<!ELEMENT jugador (nombre, apellidos, edad, equipo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT equipo (ciudad, presidente)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT presidente (nombrePresidente, apellidosPresidente)>
<!ELEMENT nombrePresidente (#PCDATA)>
<!ELEMENT apellidosPresidente (#PCDATA)>

=== josetillo/marcas/Validacion 1/liga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Jose Aranega Fernandez
Curso: 1 DAW 
Fecha: 17/03/25 
Ejercicio: Ejercicio 1 
-->
<!-- Ciudades, continentes e informacion-->
<!DOCTYPE liga SYSTEM "liga.dtd">

<liga>
    <jugador>
        <nombre>LeBron</nombre>
        <apellidos>James</apellidos>
        <edad>39</edad>
        <equipo>
            <ciudad>Los Angeles</ciudad>
            <presidente>
                <nombrePresidente>Jeanie</nombrePresidente>
                <apellidosPresidente>Buss</apellidosPresidente>
            </presidente>
        </equipo>
    </jugador>
    <jugador>
        <nombre>Stephen</nombre>
        <apellidos>Curry</apellidos>
        <edad>36</edad>
        <equipo>
            <ciudad>San Francisco</ciudad>
            <presidente>
                <nombrePresidente>Joe</nombrePresidente>
                <apellidosPresidente>Lacob</apellidosPresidente>
            </presidente>
        </equipo>
    </jugador>
    <jugador>
        <nombre>Kevin</nombre>
        <apellidos>Durant</apellidos>
        <edad>35</edad>
        <equipo>
            <ciudad>Phoenix</ciudad>
            <presidente>
                <nombrePresidente>Mat</nombrePresidente>
                <apellidosPresidente>Ishbia</apellidosPresidente>
            </presidente>
        </equipo>
    </jugador>
</liga>
